modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wolfieboy09/PortalJS/issues"

[[mods]]
    modId="portaljs"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/wolfieboy09/PortalJS/refs/heads/master/updates.json"
    #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    logoFile="portaljs.png"
    authors="${mod_authors}"

description='''${mod_description}'''

[[mixins]]
    config="portaljs.mixins.json"

[[dependencies.portaljs]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.portaljs]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
